#include <GraphicsFoundation/GraphicsFoundationPCH.h>

XII_STATICLINK_LIBRARY(GraphicsFoundation)
{
  if (bReturn)
    return;

  XII_STATICLINK_REFERENCE(GraphicsFoundation_CommandEncoder_Implementation_CommandList);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_CommandEncoder_Implementation_CommandQueue);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Declarations_Implementation_DeviceObject);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Declarations_Implementation_GraphicsTypes);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Declarations_Implementation_Object);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Device_Implementation_Device);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Device_Implementation_DeviceFactory);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Device_Implementation_SwapChain);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Profiling_Implementation_Profiling);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_BottomLevelAS);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Buffer);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_BufferView);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Fence);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Framebuffer);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Query);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_RenderPass);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Resource);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Sampler);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_Texture);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_TextureView);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Resources_Implementation_TopLevelAS);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Shader_Implementation_InputLayout);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Shader_Implementation_Shader);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Shader_Implementation_ShaderByteCode);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Shader_Implementation_ShaderResourceVariable);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_States_Implementation_BlendState);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_States_Implementation_DepthStencilState);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_States_Implementation_PipelineResourceSignature);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_States_Implementation_PipelineState);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_States_Implementation_RasterizerState);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Utilities_Implementation_DescriptorHash);
  XII_STATICLINK_REFERENCE(GraphicsFoundation_Utilities_Implementation_GraphicsUtilities);
}
